# hyper.yaml
# This is the configuration file for training

# wandb configuration
wandb_project: unet
wandb_entity: liubodong-cornell-university  # Replace with your actual entity name
wandb_mode: offline  # Set to 'offline' if you want to run without logging to Weights & Biases

# Model configuration
model_source: unet
model_type: UNet
image_size: [32, 32]
input_channels: 3
output_channels: 1
channels: [64, 128]

# Training configuration
batch_size: 2
epochs: 100
lr: 0.0003
val_split: 0.2
optimizer: Adam
loss: BCEWithLogitsLoss
save_after_epochs: 50
patience: 20
min_improvement: 0.0001
use_amp: false

# Other
device: cuda
gpu_monitoring: true
data_dir: ./data/brain_Buda/kaggle_3m
dataset: brain_mri
save_dir: ./saved_models
