# hyper_test.yaml
# This is configuration for testing the infrastructure
# of this project.

# wandb configuration
wandb_project: unet
wandb_entity: liubodong-cornell-university  # Replace with your actual entity name

# Model configuration
model_type: unet
image_size: [32, 32]
input_channels: 3
output_channels: 1
channels:
  - 32
  - 64

# Training configuration
batch_size: 1024
epochs: 100
lr: 0.001
val_split: 0.3
optimizer: Adam
loss: BCEWithLogitsLoss
save_after_epochs: 50
patience: 10
min_improvement: 0.01
use_amp: false

# Other
device:
  - cuda 0
gpu_monitoring: true
data_dir: ./data/kaggle_3m
dataset: brain_mri
save_dir: ./saved_models
