wandb_project: unet
wandb_entity: liubodong-cornell-university
wandb_mode: offline
model_source: unet
model_type: UNet
image_size:
- 256
- 256
input_channels: 3
output_channels: 1
channels:
- 64
- 128
- 256
- 512
batch_size: 20
epochs: 100
lr: 0.0003
val_split: 0.2
optimizer: Adam
loss: BCEWithLogitsLoss
save_after_epochs: 50
patience: 20
min_improvement: 0.0001
use_amp: false
device: cuda
gpu_monitoring: true
data_dir: ./data/brain_Buda/kaggle_3m
dataset: brain_mri
save_dir: ./saved_models
param_count: 8.83M
flops: 50.43G
best_epoch: 78
best_val_dice: '0.8942'
last_epoch: 98
last_val_dice: '0.8883'
