wandb_project: unet
wandb_entity: liubodong-cornell-university
model_type: attention_unet
image_size:
- 256
- 256
input_channels: 3
output_channels: 1
channels:
- 64
- 128
- 256
- 512
batch_size: 16
epochs: 100
lr: 0.0003
val_split: 0.2
optimizer: Adam
loss: BCEWithLogitsLoss
save_after_epochs: 50
patience: 20
min_improvement: 0.0001
use_amp: false
device:
- cuda 0
gpu_monitoring: true
data_dir: ./data/brain_Buda/kaggle_3m
dataset: brain_mri
save_dir: ./saved_models
param_count: 8.83M
flops: 50.43G
best_epoch: 81
best_val_dice: '0.9117'
last_epoch: 100
last_val_dice: '0.9098'
